<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Grupy', 'doctrine');

/**
 * BaseGrupy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pupil
 * @property integer $semestr_id
 * @property integer $grupa
 * @property string $info
 * @property Uzytkownik $Uzytkownik
 * @property Semestr $Semestr
 * @property Doctrine_Collection $Planlekcji
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getPupil()      Returns the current record's "pupil" value
 * @method integer             getSemestrId()  Returns the current record's "semestr_id" value
 * @method integer             getGrupa()      Returns the current record's "grupa" value
 * @method string              getInfo()       Returns the current record's "info" value
 * @method Uzytkownik          getUzytkownik() Returns the current record's "Uzytkownik" value
 * @method Semestr             getSemestr()    Returns the current record's "Semestr" value
 * @method Doctrine_Collection getPlanlekcji() Returns the current record's "Planlekcji" collection
 * @method Grupy               setId()         Sets the current record's "id" value
 * @method Grupy               setPupil()      Sets the current record's "pupil" value
 * @method Grupy               setSemestrId()  Sets the current record's "semestr_id" value
 * @method Grupy               setGrupa()      Sets the current record's "grupa" value
 * @method Grupy               setInfo()       Sets the current record's "info" value
 * @method Grupy               setUzytkownik() Sets the current record's "Uzytkownik" value
 * @method Grupy               setSemestr()    Sets the current record's "Semestr" value
 * @method Grupy               setPlanlekcji() Sets the current record's "Planlekcji" collection
 * 
 * @package    edziennik
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrupy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupy');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'grupy_id',
             'length' => 4,
             ));
        $this->hasColumn('pupil', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('semestr_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('grupa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('info', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Uzytkownik', array(
             'local' => 'pupil',
             'foreign' => 'id'));

        $this->hasOne('Semestr', array(
             'local' => 'semestr_id',
             'foreign' => 'id'));

        $this->hasMany('Planlekcji', array(
             'local' => 'id',
             'foreign' => 'grupa_id'));
    }
}