<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Uwagi', 'doctrine');

/**
 * BaseUwagi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pupil
 * @property integer $lekcja_id
 * @property string $info
 * @property Lekcje $Lekcje
 * @property Uzytkownik $Uzytkownik
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method integer    getPupil()      Returns the current record's "pupil" value
 * @method integer    getLekcjaId()   Returns the current record's "lekcja_id" value
 * @method string     getInfo()       Returns the current record's "info" value
 * @method Lekcje     getLekcje()     Returns the current record's "Lekcje" value
 * @method Uzytkownik getUzytkownik() Returns the current record's "Uzytkownik" value
 * @method Uwagi      setId()         Sets the current record's "id" value
 * @method Uwagi      setPupil()      Sets the current record's "pupil" value
 * @method Uwagi      setLekcjaId()   Sets the current record's "lekcja_id" value
 * @method Uwagi      setInfo()       Sets the current record's "info" value
 * @method Uwagi      setLekcje()     Sets the current record's "Lekcje" value
 * @method Uwagi      setUzytkownik() Sets the current record's "Uzytkownik" value
 * 
 * @package    edziennik
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUwagi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uwagi');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'uwagi_id',
             'length' => 4,
             ));
        $this->hasColumn('pupil', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('lekcja_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('info', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Lekcje', array(
             'local' => 'lekcja_id',
             'foreign' => 'id'));

        $this->hasOne('Uzytkownik', array(
             'local' => 'pupil',
             'foreign' => 'id'));
    }
}