<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Semestr', 'doctrine');

/**
 * BaseSemestr
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $rok
 * @property string $polowa
 * @property Doctrine_Collection $Oceny
 * @property Doctrine_Collection $Dyplomy
 * @property Doctrine_Collection $Planlekcji
 * @property Doctrine_Collection $Lekcje
 * @property Doctrine_Collection $Grupy
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getRok()        Returns the current record's "rok" value
 * @method string              getPolowa()     Returns the current record's "polowa" value
 * @method Doctrine_Collection getOceny()      Returns the current record's "Oceny" collection
 * @method Doctrine_Collection getDyplomy()    Returns the current record's "Dyplomy" collection
 * @method Doctrine_Collection getPlanlekcji() Returns the current record's "Planlekcji" collection
 * @method Doctrine_Collection getLekcje()     Returns the current record's "Lekcje" collection
 * @method Doctrine_Collection getGrupy()      Returns the current record's "Grupy" collection
 * @method Semestr             setId()         Sets the current record's "id" value
 * @method Semestr             setRok()        Sets the current record's "rok" value
 * @method Semestr             setPolowa()     Sets the current record's "polowa" value
 * @method Semestr             setOceny()      Sets the current record's "Oceny" collection
 * @method Semestr             setDyplomy()    Sets the current record's "Dyplomy" collection
 * @method Semestr             setPlanlekcji() Sets the current record's "Planlekcji" collection
 * @method Semestr             setLekcje()     Sets the current record's "Lekcje" collection
 * @method Semestr             setGrupy()      Sets the current record's "Grupy" collection
 * 
 * @package    edziennik
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSemestr extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('semestr');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'semestr_id',
             'length' => 4,
             ));
        $this->hasColumn('rok', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('polowa', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Oceny', array(
             'local' => 'id',
             'foreign' => 'semestr_id'));

        $this->hasMany('Dyplomy', array(
             'local' => 'id',
             'foreign' => 'semestr_id'));

        $this->hasMany('Planlekcji', array(
             'local' => 'id',
             'foreign' => 'semestr_id'));

        $this->hasMany('Lekcje', array(
             'local' => 'id',
             'foreign' => 'semestr_id'));

        $this->hasMany('Grupy', array(
             'local' => 'id',
             'foreign' => 'semestr_id'));
    }
}