<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usprawiedliwienie', 'doctrine');

/**
 * BaseUsprawiedliwienie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $obecnosci_id
 * @property integer $uzytkownik_id
 * @property string $tresc
 * @property Obecnosci $Obecnosci
 * @property Uzytkownik $Uzytkownik
 * 
 * @method integer           getId()            Returns the current record's "id" value
 * @method integer           getObecnosciId()   Returns the current record's "obecnosci_id" value
 * @method integer           getUzytkownikId()  Returns the current record's "uzytkownik_id" value
 * @method string            getTresc()         Returns the current record's "tresc" value
 * @method Obecnosci         getObecnosci()     Returns the current record's "Obecnosci" value
 * @method Uzytkownik        getUzytkownik()    Returns the current record's "Uzytkownik" value
 * @method Usprawiedliwienie setId()            Sets the current record's "id" value
 * @method Usprawiedliwienie setObecnosciId()   Sets the current record's "obecnosci_id" value
 * @method Usprawiedliwienie setUzytkownikId()  Sets the current record's "uzytkownik_id" value
 * @method Usprawiedliwienie setTresc()         Sets the current record's "tresc" value
 * @method Usprawiedliwienie setObecnosci()     Sets the current record's "Obecnosci" value
 * @method Usprawiedliwienie setUzytkownik()    Sets the current record's "Uzytkownik" value
 * 
 * @package    edziennik
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsprawiedliwienie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usprawiedliwienie');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('obecnosci_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('uzytkownik_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('tresc', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Obecnosci', array(
             'local' => 'obecnosci_id',
             'foreign' => 'id'));

        $this->hasOne('Uzytkownik', array(
             'local' => 'uzytkownik_id',
             'foreign' => 'id'));
    }
}