<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tablicaocen', 'doctrine');

/**
 * BaseTablicaocen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nazwa
 * @property float $wartosc
 * @property Doctrine_Collection $Oceny
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getNazwa()   Returns the current record's "nazwa" value
 * @method float               getWartosc() Returns the current record's "wartosc" value
 * @method Doctrine_Collection getOceny()   Returns the current record's "Oceny" collection
 * @method Tablicaocen         setId()      Sets the current record's "id" value
 * @method Tablicaocen         setNazwa()   Sets the current record's "nazwa" value
 * @method Tablicaocen         setWartosc() Sets the current record's "wartosc" value
 * @method Tablicaocen         setOceny()   Sets the current record's "Oceny" collection
 * 
 * @package    edziennik
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTablicaocen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tablicaocen');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tablicaocen_id',
             'length' => 4,
             ));
        $this->hasColumn('nazwa', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('wartosc', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Oceny', array(
             'local' => 'id',
             'foreign' => 'ocena_id'));
    }
}