<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Przedmiot', 'doctrine');

/**
 * BasePrzedmiot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nazwa
 * @property Doctrine_Collection $Oceny
 * @property Doctrine_Collection $Dyplomy
 * @property Doctrine_Collection $Planlekcji
 * @property Doctrine_Collection $Lekcje
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getNazwa()      Returns the current record's "nazwa" value
 * @method Doctrine_Collection getOceny()      Returns the current record's "Oceny" collection
 * @method Doctrine_Collection getDyplomy()    Returns the current record's "Dyplomy" collection
 * @method Doctrine_Collection getPlanlekcji() Returns the current record's "Planlekcji" collection
 * @method Doctrine_Collection getLekcje()     Returns the current record's "Lekcje" collection
 * @method Przedmiot           setId()         Sets the current record's "id" value
 * @method Przedmiot           setNazwa()      Sets the current record's "nazwa" value
 * @method Przedmiot           setOceny()      Sets the current record's "Oceny" collection
 * @method Przedmiot           setDyplomy()    Sets the current record's "Dyplomy" collection
 * @method Przedmiot           setPlanlekcji() Sets the current record's "Planlekcji" collection
 * @method Przedmiot           setLekcje()     Sets the current record's "Lekcje" collection
 * 
 * @package    edziennik
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrzedmiot extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('przedmiot');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'przedmiot_id',
             'length' => 4,
             ));
        $this->hasColumn('nazwa', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Oceny', array(
             'local' => 'id',
             'foreign' => 'przedmiot_id'));

        $this->hasMany('Dyplomy', array(
             'local' => 'id',
             'foreign' => 'przedmiot_id'));

        $this->hasMany('Planlekcji', array(
             'local' => 'id',
             'foreign' => 'przedmiot_id'));

        $this->hasMany('Lekcje', array(
             'local' => 'id',
             'foreign' => 'przedmiot_id'));
    }
}