<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Uzytkownik', 'doctrine');

/**
 * BaseUzytkownik
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $rodzaj
 * @property string $imie
 * @property string $nazwisko
 * @property string $login
 * @property string $haslo
 * @property string $email
 * @property string $telefon
 * @property integer $klasa_id
 * @property integer $pesel
 * @property date $dataurodzin
 * @property date $miejsceurodzin
 * @property integer $ojciec
 * @property integer $matka
 * @property string $ulica
 * @property string $nrdomu
 * @property string $kodpocztowy
 * @property string $panstwo
 * @property string $info
 * @property boolean $aktywny
 * @property Doctrine_Collection $Klasy
 * @property Doctrine_Collection $Uzytkownik
 * @property Doctrine_Collection $Uzytkownik_3
 * @property Doctrine_Collection $Oceny
 * @property Doctrine_Collection $Oceny_4
 * @property Doctrine_Collection $Usprawiedliwienie
 * @property Doctrine_Collection $Dyplomy
 * @property Doctrine_Collection $Planlekcji
 * @property Doctrine_Collection $Uwagi
 * @property Doctrine_Collection $Lekcje
 * @property Doctrine_Collection $Grupy
 * @property Doctrine_Collection $Obecnosci
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getRodzaj()            Returns the current record's "rodzaj" value
 * @method string              getImie()              Returns the current record's "imie" value
 * @method string              getNazwisko()          Returns the current record's "nazwisko" value
 * @method string              getLogin()             Returns the current record's "login" value
 * @method string              getHaslo()             Returns the current record's "haslo" value
 * @method string              getEmail()             Returns the current record's "email" value
 * @method string              getTelefon()           Returns the current record's "telefon" value
 * @method integer             getKlasaId()           Returns the current record's "klasa_id" value
 * @method integer             getPesel()             Returns the current record's "pesel" value
 * @method date                getDataurodzin()       Returns the current record's "dataurodzin" value
 * @method date                getMiejsceurodzin()    Returns the current record's "miejsceurodzin" value
 * @method integer             getOjciec()            Returns the current record's "ojciec" value
 * @method integer             getMatka()             Returns the current record's "matka" value
 * @method string              getUlica()             Returns the current record's "ulica" value
 * @method string              getNrdomu()            Returns the current record's "nrdomu" value
 * @method string              getKodpocztowy()       Returns the current record's "kodpocztowy" value
 * @method string              getPanstwo()           Returns the current record's "panstwo" value
 * @method string              getInfo()              Returns the current record's "info" value
 * @method boolean             getAktywny()           Returns the current record's "aktywny" value
 * @method Doctrine_Collection getKlasy()             Returns the current record's "Klasy" collection
 * @method Doctrine_Collection getUzytkownik()        Returns the current record's "Uzytkownik" collection
 * @method Doctrine_Collection getUzytkownik3()       Returns the current record's "Uzytkownik_3" collection
 * @method Doctrine_Collection getOceny()             Returns the current record's "Oceny" collection
 * @method Doctrine_Collection getOceny4()            Returns the current record's "Oceny_4" collection
 * @method Doctrine_Collection getUsprawiedliwienie() Returns the current record's "Usprawiedliwienie" collection
 * @method Doctrine_Collection getDyplomy()           Returns the current record's "Dyplomy" collection
 * @method Doctrine_Collection getPlanlekcji()        Returns the current record's "Planlekcji" collection
 * @method Doctrine_Collection getUwagi()             Returns the current record's "Uwagi" collection
 * @method Doctrine_Collection getLekcje()            Returns the current record's "Lekcje" collection
 * @method Doctrine_Collection getGrupy()             Returns the current record's "Grupy" collection
 * @method Doctrine_Collection getObecnosci()         Returns the current record's "Obecnosci" collection
 * @method Uzytkownik          setId()                Sets the current record's "id" value
 * @method Uzytkownik          setRodzaj()            Sets the current record's "rodzaj" value
 * @method Uzytkownik          setImie()              Sets the current record's "imie" value
 * @method Uzytkownik          setNazwisko()          Sets the current record's "nazwisko" value
 * @method Uzytkownik          setLogin()             Sets the current record's "login" value
 * @method Uzytkownik          setHaslo()             Sets the current record's "haslo" value
 * @method Uzytkownik          setEmail()             Sets the current record's "email" value
 * @method Uzytkownik          setTelefon()           Sets the current record's "telefon" value
 * @method Uzytkownik          setKlasaId()           Sets the current record's "klasa_id" value
 * @method Uzytkownik          setPesel()             Sets the current record's "pesel" value
 * @method Uzytkownik          setDataurodzin()       Sets the current record's "dataurodzin" value
 * @method Uzytkownik          setMiejsceurodzin()    Sets the current record's "miejsceurodzin" value
 * @method Uzytkownik          setOjciec()            Sets the current record's "ojciec" value
 * @method Uzytkownik          setMatka()             Sets the current record's "matka" value
 * @method Uzytkownik          setUlica()             Sets the current record's "ulica" value
 * @method Uzytkownik          setNrdomu()            Sets the current record's "nrdomu" value
 * @method Uzytkownik          setKodpocztowy()       Sets the current record's "kodpocztowy" value
 * @method Uzytkownik          setPanstwo()           Sets the current record's "panstwo" value
 * @method Uzytkownik          setInfo()              Sets the current record's "info" value
 * @method Uzytkownik          setAktywny()           Sets the current record's "aktywny" value
 * @method Uzytkownik          setKlasy()             Sets the current record's "Klasy" collection
 * @method Uzytkownik          setUzytkownik()        Sets the current record's "Uzytkownik" collection
 * @method Uzytkownik          setUzytkownik3()       Sets the current record's "Uzytkownik_3" collection
 * @method Uzytkownik          setOceny()             Sets the current record's "Oceny" collection
 * @method Uzytkownik          setOceny4()            Sets the current record's "Oceny_4" collection
 * @method Uzytkownik          setUsprawiedliwienie() Sets the current record's "Usprawiedliwienie" collection
 * @method Uzytkownik          setDyplomy()           Sets the current record's "Dyplomy" collection
 * @method Uzytkownik          setPlanlekcji()        Sets the current record's "Planlekcji" collection
 * @method Uzytkownik          setUwagi()             Sets the current record's "Uwagi" collection
 * @method Uzytkownik          setLekcje()            Sets the current record's "Lekcje" collection
 * @method Uzytkownik          setGrupy()             Sets the current record's "Grupy" collection
 * @method Uzytkownik          setObecnosci()         Sets the current record's "Obecnosci" collection
 * 
 * @package    edziennik
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUzytkownik extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uzytkownik');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'uzytkownik_id',
             'length' => 4,
             ));
        $this->hasColumn('rodzaj', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 6,
             ));
        $this->hasColumn('imie', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nazwisko', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('login', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('haslo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefon', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('klasa_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('pesel', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('dataurodzin', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('miejsceurodzin', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('ojciec', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('matka', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ulica', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nrdomu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('kodpocztowy', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('panstwo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('info', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('aktywny', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'true',
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Klasy', array(
             'local' => 'id',
             'foreign' => 'wychowawca'));

        $this->hasMany('Uzytkownik', array(
             'local' => 'id',
             'foreign' => 'matka'));

        $this->hasMany('Uzytkownik as Uzytkownik_3', array(
             'local' => 'id',
             'foreign' => 'ojciec'));

        $this->hasMany('Oceny', array(
             'local' => 'id',
             'foreign' => 'nauczyciel_id'));

        $this->hasMany('Oceny as Oceny_4', array(
             'local' => 'id',
             'foreign' => 'pupil'));

        $this->hasMany('Usprawiedliwienie', array(
             'local' => 'id',
             'foreign' => 'uzytkownik_id'));

        $this->hasMany('Dyplomy', array(
             'local' => 'id',
             'foreign' => 'pupil'));

        $this->hasMany('Planlekcji', array(
             'local' => 'id',
             'foreign' => 'nauczyciel_id'));

        $this->hasMany('Uwagi', array(
             'local' => 'id',
             'foreign' => 'pupil'));

        $this->hasMany('Lekcje', array(
             'local' => 'id',
             'foreign' => 'nauczyciel_id'));

        $this->hasMany('Grupy', array(
             'local' => 'id',
             'foreign' => 'pupil'));

        $this->hasMany('Obecnosci', array(
             'local' => 'id',
             'foreign' => 'pupil'));
    }
}