<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Dyplomy', 'doctrine');

/**
 * BaseDyplomy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pupil
 * @property integer $semestr_id
 * @property integer $przedmiot_id
 * @property integer $ocenadyplomu
 * @property Przedmiot $Przedmiot
 * @property Uzytkownik $Uzytkownik
 * @property Semestr $Semestr
 * 
 * @method integer    getId()           Returns the current record's "id" value
 * @method integer    getPupil()        Returns the current record's "pupil" value
 * @method integer    getSemestrId()    Returns the current record's "semestr_id" value
 * @method integer    getPrzedmiotId()  Returns the current record's "przedmiot_id" value
 * @method integer    getOcenadyplomu() Returns the current record's "ocenadyplomu" value
 * @method Przedmiot  getPrzedmiot()    Returns the current record's "Przedmiot" value
 * @method Uzytkownik getUzytkownik()   Returns the current record's "Uzytkownik" value
 * @method Semestr    getSemestr()      Returns the current record's "Semestr" value
 * @method Dyplomy    setId()           Sets the current record's "id" value
 * @method Dyplomy    setPupil()        Sets the current record's "pupil" value
 * @method Dyplomy    setSemestrId()    Sets the current record's "semestr_id" value
 * @method Dyplomy    setPrzedmiotId()  Sets the current record's "przedmiot_id" value
 * @method Dyplomy    setOcenadyplomu() Sets the current record's "ocenadyplomu" value
 * @method Dyplomy    setPrzedmiot()    Sets the current record's "Przedmiot" value
 * @method Dyplomy    setUzytkownik()   Sets the current record's "Uzytkownik" value
 * @method Dyplomy    setSemestr()      Sets the current record's "Semestr" value
 * 
 * @package    edziennik
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDyplomy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dyplomy');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'dyplomy_id',
             'length' => 4,
             ));
        $this->hasColumn('pupil', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('semestr_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('przedmiot_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ocenadyplomu', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Przedmiot', array(
             'local' => 'przedmiot_id',
             'foreign' => 'id'));

        $this->hasOne('Uzytkownik', array(
             'local' => 'pupil',
             'foreign' => 'id'));

        $this->hasOne('Semestr', array(
             'local' => 'semestr_id',
             'foreign' => 'id'));
    }
}