<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Klasy', 'doctrine');

/**
 * BaseKlasy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $poziom
 * @property string $znak
 * @property string $opis
 * @property integer $wychowawca
 * @property integer $startsemestr
 * @property Doctrine_Collection $Uzytkownik
 * @property Doctrine_Collection $Planlekcji
 * @property Doctrine_Collection $Lekcje
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getPoziom()       Returns the current record's "poziom" value
 * @method string              getZnak()         Returns the current record's "znak" value
 * @method string              getOpis()         Returns the current record's "opis" value
 * @method integer             getWychowawca()   Returns the current record's "wychowawca" value
 * @method integer             getStartsemestr() Returns the current record's "startsemestr" value
 * @method Doctrine_Collection getUzytkownik()   Returns the current record's "Uzytkownik" collection
 * @method Doctrine_Collection getPlanlekcji()   Returns the current record's "Planlekcji" collection
 * @method Doctrine_Collection getLekcje()       Returns the current record's "Lekcje" collection
 * @method Klasy               setId()           Sets the current record's "id" value
 * @method Klasy               setPoziom()       Sets the current record's "poziom" value
 * @method Klasy               setZnak()         Sets the current record's "znak" value
 * @method Klasy               setOpis()         Sets the current record's "opis" value
 * @method Klasy               setWychowawca()   Sets the current record's "wychowawca" value
 * @method Klasy               setStartsemestr() Sets the current record's "startsemestr" value
 * @method Klasy               setUzytkownik()   Sets the current record's "Uzytkownik" collection
 * @method Klasy               setPlanlekcji()   Sets the current record's "Planlekcji" collection
 * @method Klasy               setLekcje()       Sets the current record's "Lekcje" collection
 * 
 * @package    edziennik
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKlasy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('klasy');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'klasy_id',
             'length' => 4,
             ));
        $this->hasColumn('poziom', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('znak', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('opis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('wychowawca', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('startsemestr', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Uzytkownik', array(
             'local' => 'id',
             'foreign' => 'klasa_id'));

        $this->hasMany('Planlekcji', array(
             'local' => 'id',
             'foreign' => 'klasa_id'));

        $this->hasMany('Lekcje', array(
             'local' => 'id',
             'foreign' => 'klasa_id'));
    }
}