# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

default:
  is_secure: false
  
uczen:
  is_secure: true
  credentials: uczen
  
rodzic:
  is_secure: true
  credentials: rodzic
  
nauczyciel:
  is_secure: true
  credentials: naucz
  
sekretariat:
  is_secure: true
  credentials: sekret
  
admin:
  is_secure: true
  credentials: admin
  
dodajg:
  is_secure: true
  credentials: admin
  
dodajk:
  is_secure: true
  credentials: admin
  
dodajpl:
  is_secure: true
  credentials: admin
  
dodajse:
  is_secure: true
  credentials: admin
  
dodajto:
  is_secure: true
  credentials: admin
  
dodaju:
  is_secure: true
  credentials: admin
  
grupy:
  is_secure: true
  credentials: admin
  
klasy:
  is_secure: true
  credentials: admin
  
mkonto:
  is_secure: true
  credentials: admin
  
planlekcji:
  is_secure: true
  credentials: admin
  
semestry:
  is_secure: true
  credentials: admin
  
tablicaocen:
  is_secure: true
  credentials: admin
  
users:
  is_secure: true
  credentials: admin