# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

default:
  is_secure: false
  
uczen:
  is_secure: true
  credentials: uczen
  
rodzic:
  is_secure: true
  credentials: rodzic
  
nauczyciel:
  is_secure: true
  credentials: naucz
  
sekretariat:
  is_secure: true
  credentials: sekret
  
admin:
  is_secure: true
  credentials: admin
  
dodajg:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
dodajk:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
dodajpl:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
dodajse:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
dodajto:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
dodaju:
  is_secure: true
  credentials: [[ admin, sekret ]] 

zapiszg:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
zapiszk:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
zapiszpl:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
zapiszse:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
zapiszto:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
zapiszu:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
grupy:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
klasy:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
mkonto:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
planlekcji:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
semestry:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
tablicaocen:
  is_secure: true
  credentials: [[ admin, sekret ]] 
  
users:
  is_secure: true
  credentials: [[ admin, sekret ]] 