# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

default:
  is_secure: false
  
uczen:
  is_secure: on
  credentials: uczen
  
rodzic:
  is_secure: on
  credentials: rodzic
  
nauczyciel:
  is_secure: on
  credentials: naucz
  
sekretariat:
  is_secure: on
  credentials: sekret
  
admin:
  is_secure: on
  credentials: admin