<?php


/**
 * This class defines the structure of the 'planlekcji' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 16 19:12:44 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PlanlekcjiTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PlanlekcjiTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('planlekcji');
		$this->setPhpName('Planlekcji');
		$this->setClassname('Planlekcji');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('SEMESTR_ID', 'SemestrId', 'INTEGER', 'semestr', 'ID', true, null, null);
		$this->addForeignKey('KLASA_ID', 'KlasaId', 'INTEGER', 'klasy', 'ID', true, null, null);
		$this->addForeignKey('NAUCZYCIEL_ID', 'NauczycielId', 'INTEGER', 'uzytkownik', 'ID', true, null, null);
		$this->addForeignKey('PRZEDMIOT_ID', 'PrzedmiotId', 'INTEGER', 'przedmiot', 'ID', true, null, null);
		$this->addColumn('CZASSTART', 'Czasstart', 'DATE', false, null, null);
		$this->addColumn('CZASSTOP', 'Czasstop', 'DATE', false, null, null);
		$this->addColumn('DZIENTYGODNIA', 'Dzientygodnia', 'INTEGER', false, null, null);
		$this->addColumn('GODZINALEKCYJNA', 'Godzinalekcyjna', 'INTEGER', false, null, null);
		$this->addForeignKey('GRUPA_ID', 'GrupaId', 'INTEGER', 'grupy', 'ID', false, null, null);
		$this->addColumn('OBOWIAZKOWA', 'Obowiazkowa', 'BOOLEAN', true, null, true);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Semestr', 'Semestr', RelationMap::MANY_TO_ONE, array('semestr_id' => 'id', ), null, null);
    $this->addRelation('Klasy', 'Klasy', RelationMap::MANY_TO_ONE, array('klasa_id' => 'id', ), null, null);
    $this->addRelation('Uzytkownik', 'Uzytkownik', RelationMap::MANY_TO_ONE, array('nauczyciel_id' => 'id', ), null, null);
    $this->addRelation('Przedmiot', 'Przedmiot', RelationMap::MANY_TO_ONE, array('przedmiot_id' => 'id', ), null, null);
    $this->addRelation('Grupy', 'Grupy', RelationMap::MANY_TO_ONE, array('grupa_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // PlanlekcjiTableMap
