<?php

/**
 * Base class that represents a row from the 'klasy' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Jun 24 12:49:10 2012
 *
 * @package    lib.model.om
 */
abstract class BaseKlasy extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        KlasyPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the poziom field.
	 * @var        int
	 */
	protected $poziom;

	/**
	 * The value for the znak field.
	 * @var        string
	 */
	protected $znak;

	/**
	 * The value for the opis field.
	 * @var        string
	 */
	protected $opis;

	/**
	 * The value for the wychowawca field.
	 * @var        int
	 */
	protected $wychowawca;

	/**
	 * The value for the startsemestr field.
	 * @var        int
	 */
	protected $startsemestr;

	/**
	 * @var        array Lekcje[] Collection to store aggregation of Lekcje objects.
	 */
	protected $collLekcjes;

	/**
	 * @var        Criteria The criteria used to select the current contents of collLekcjes.
	 */
	private $lastLekcjeCriteria = null;

	/**
	 * @var        array Planlekcji[] Collection to store aggregation of Planlekcji objects.
	 */
	protected $collPlanlekcjis;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPlanlekcjis.
	 */
	private $lastPlanlekcjiCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'KlasyPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [poziom] column value.
	 * 
	 * @return     int
	 */
	public function getPoziom()
	{
		return $this->poziom;
	}

	/**
	 * Get the [znak] column value.
	 * 
	 * @return     string
	 */
	public function getZnak()
	{
		return $this->znak;
	}

	/**
	 * Get the [opis] column value.
	 * 
	 * @return     string
	 */
	public function getOpis()
	{
		return $this->opis;
	}

	/**
	 * Get the [wychowawca] column value.
	 * 
	 * @return     int
	 */
	public function getWychowawca()
	{
		return $this->wychowawca;
	}

	/**
	 * Get the [startsemestr] column value.
	 * 
	 * @return     int
	 */
	public function getStartsemestr()
	{
		return $this->startsemestr;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Klasy The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = KlasyPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [poziom] column.
	 * 
	 * @param      int $v new value
	 * @return     Klasy The current object (for fluent API support)
	 */
	public function setPoziom($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->poziom !== $v) {
			$this->poziom = $v;
			$this->modifiedColumns[] = KlasyPeer::POZIOM;
		}

		return $this;
	} // setPoziom()

	/**
	 * Set the value of [znak] column.
	 * 
	 * @param      string $v new value
	 * @return     Klasy The current object (for fluent API support)
	 */
	public function setZnak($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->znak !== $v) {
			$this->znak = $v;
			$this->modifiedColumns[] = KlasyPeer::ZNAK;
		}

		return $this;
	} // setZnak()

	/**
	 * Set the value of [opis] column.
	 * 
	 * @param      string $v new value
	 * @return     Klasy The current object (for fluent API support)
	 */
	public function setOpis($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->opis !== $v) {
			$this->opis = $v;
			$this->modifiedColumns[] = KlasyPeer::OPIS;
		}

		return $this;
	} // setOpis()

	/**
	 * Set the value of [wychowawca] column.
	 * 
	 * @param      int $v new value
	 * @return     Klasy The current object (for fluent API support)
	 */
	public function setWychowawca($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->wychowawca !== $v) {
			$this->wychowawca = $v;
			$this->modifiedColumns[] = KlasyPeer::WYCHOWAWCA;
		}

		return $this;
	} // setWychowawca()

	/**
	 * Set the value of [startsemestr] column.
	 * 
	 * @param      int $v new value
	 * @return     Klasy The current object (for fluent API support)
	 */
	public function setStartsemestr($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->startsemestr !== $v) {
			$this->startsemestr = $v;
			$this->modifiedColumns[] = KlasyPeer::STARTSEMESTR;
		}

		return $this;
	} // setStartsemestr()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->poziom = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->znak = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->opis = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->wychowawca = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->startsemestr = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 6; // 6 = KlasyPeer::NUM_COLUMNS - KlasyPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Klasy object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(KlasyPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = KlasyPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collLekcjes = null;
			$this->lastLekcjeCriteria = null;

			$this->collPlanlekcjis = null;
			$this->lastPlanlekcjiCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(KlasyPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseKlasy:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				KlasyPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseKlasy:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(KlasyPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseKlasy:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseKlasy:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				KlasyPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = KlasyPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += KlasyPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collLekcjes !== null) {
				foreach ($this->collLekcjes as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPlanlekcjis !== null) {
				foreach ($this->collPlanlekcjis as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = KlasyPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collLekcjes !== null) {
					foreach ($this->collLekcjes as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPlanlekcjis !== null) {
					foreach ($this->collPlanlekcjis as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = KlasyPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPoziom();
				break;
			case 2:
				return $this->getZnak();
				break;
			case 3:
				return $this->getOpis();
				break;
			case 4:
				return $this->getWychowawca();
				break;
			case 5:
				return $this->getStartsemestr();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = KlasyPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPoziom(),
			$keys[2] => $this->getZnak(),
			$keys[3] => $this->getOpis(),
			$keys[4] => $this->getWychowawca(),
			$keys[5] => $this->getStartsemestr(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = KlasyPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPoziom($value);
				break;
			case 2:
				$this->setZnak($value);
				break;
			case 3:
				$this->setOpis($value);
				break;
			case 4:
				$this->setWychowawca($value);
				break;
			case 5:
				$this->setStartsemestr($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = KlasyPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPoziom($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setZnak($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setOpis($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setWychowawca($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setStartsemestr($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(KlasyPeer::DATABASE_NAME);

		if ($this->isColumnModified(KlasyPeer::ID)) $criteria->add(KlasyPeer::ID, $this->id);
		if ($this->isColumnModified(KlasyPeer::POZIOM)) $criteria->add(KlasyPeer::POZIOM, $this->poziom);
		if ($this->isColumnModified(KlasyPeer::ZNAK)) $criteria->add(KlasyPeer::ZNAK, $this->znak);
		if ($this->isColumnModified(KlasyPeer::OPIS)) $criteria->add(KlasyPeer::OPIS, $this->opis);
		if ($this->isColumnModified(KlasyPeer::WYCHOWAWCA)) $criteria->add(KlasyPeer::WYCHOWAWCA, $this->wychowawca);
		if ($this->isColumnModified(KlasyPeer::STARTSEMESTR)) $criteria->add(KlasyPeer::STARTSEMESTR, $this->startsemestr);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(KlasyPeer::DATABASE_NAME);

		$criteria->add(KlasyPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Klasy (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setId($this->id);

		$copyObj->setPoziom($this->poziom);

		$copyObj->setZnak($this->znak);

		$copyObj->setOpis($this->opis);

		$copyObj->setWychowawca($this->wychowawca);

		$copyObj->setStartsemestr($this->startsemestr);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getLekcjes() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addLekcje($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPlanlekcjis() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPlanlekcji($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Klasy Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     KlasyPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new KlasyPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collLekcjes collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addLekcjes()
	 */
	public function clearLekcjes()
	{
		$this->collLekcjes = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collLekcjes collection (array).
	 *
	 * By default this just sets the collLekcjes collection to an empty array (like clearcollLekcjes());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initLekcjes()
	{
		$this->collLekcjes = array();
	}

	/**
	 * Gets an array of Lekcje objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Klasy has previously been saved, it will retrieve
	 * related Lekcjes from storage. If this Klasy is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Lekcje[]
	 * @throws     PropelException
	 */
	public function getLekcjes($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(KlasyPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLekcjes === null) {
			if ($this->isNew()) {
			   $this->collLekcjes = array();
			} else {

				$criteria->add(LekcjePeer::KLASA_ID, $this->id);

				LekcjePeer::addSelectColumns($criteria);
				$this->collLekcjes = LekcjePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(LekcjePeer::KLASA_ID, $this->id);

				LekcjePeer::addSelectColumns($criteria);
				if (!isset($this->lastLekcjeCriteria) || !$this->lastLekcjeCriteria->equals($criteria)) {
					$this->collLekcjes = LekcjePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastLekcjeCriteria = $criteria;
		return $this->collLekcjes;
	}

	/**
	 * Returns the number of related Lekcje objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Lekcje objects.
	 * @throws     PropelException
	 */
	public function countLekcjes(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(KlasyPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collLekcjes === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(LekcjePeer::KLASA_ID, $this->id);

				$count = LekcjePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(LekcjePeer::KLASA_ID, $this->id);

				if (!isset($this->lastLekcjeCriteria) || !$this->lastLekcjeCriteria->equals($criteria)) {
					$count = LekcjePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collLekcjes);
				}
			} else {
				$count = count($this->collLekcjes);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Lekcje object to this object
	 * through the Lekcje foreign key attribute.
	 *
	 * @param      Lekcje $l Lekcje
	 * @return     void
	 * @throws     PropelException
	 */
	public function addLekcje(Lekcje $l)
	{
		if ($this->collLekcjes === null) {
			$this->initLekcjes();
		}
		if (!in_array($l, $this->collLekcjes, true)) { // only add it if the **same** object is not already associated
			array_push($this->collLekcjes, $l);
			$l->setKlasy($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Klasy is new, it will return
	 * an empty collection; or if this Klasy has previously
	 * been saved, it will retrieve related Lekcjes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Klasy.
	 */
	public function getLekcjesJoinPrzedmiot($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(KlasyPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLekcjes === null) {
			if ($this->isNew()) {
				$this->collLekcjes = array();
			} else {

				$criteria->add(LekcjePeer::KLASA_ID, $this->id);

				$this->collLekcjes = LekcjePeer::doSelectJoinPrzedmiot($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(LekcjePeer::KLASA_ID, $this->id);

			if (!isset($this->lastLekcjeCriteria) || !$this->lastLekcjeCriteria->equals($criteria)) {
				$this->collLekcjes = LekcjePeer::doSelectJoinPrzedmiot($criteria, $con, $join_behavior);
			}
		}
		$this->lastLekcjeCriteria = $criteria;

		return $this->collLekcjes;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Klasy is new, it will return
	 * an empty collection; or if this Klasy has previously
	 * been saved, it will retrieve related Lekcjes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Klasy.
	 */
	public function getLekcjesJoinSemestr($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(KlasyPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLekcjes === null) {
			if ($this->isNew()) {
				$this->collLekcjes = array();
			} else {

				$criteria->add(LekcjePeer::KLASA_ID, $this->id);

				$this->collLekcjes = LekcjePeer::doSelectJoinSemestr($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(LekcjePeer::KLASA_ID, $this->id);

			if (!isset($this->lastLekcjeCriteria) || !$this->lastLekcjeCriteria->equals($criteria)) {
				$this->collLekcjes = LekcjePeer::doSelectJoinSemestr($criteria, $con, $join_behavior);
			}
		}
		$this->lastLekcjeCriteria = $criteria;

		return $this->collLekcjes;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Klasy is new, it will return
	 * an empty collection; or if this Klasy has previously
	 * been saved, it will retrieve related Lekcjes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Klasy.
	 */
	public function getLekcjesJoinUzytkownik($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(KlasyPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLekcjes === null) {
			if ($this->isNew()) {
				$this->collLekcjes = array();
			} else {

				$criteria->add(LekcjePeer::KLASA_ID, $this->id);

				$this->collLekcjes = LekcjePeer::doSelectJoinUzytkownik($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(LekcjePeer::KLASA_ID, $this->id);

			if (!isset($this->lastLekcjeCriteria) || !$this->lastLekcjeCriteria->equals($criteria)) {
				$this->collLekcjes = LekcjePeer::doSelectJoinUzytkownik($criteria, $con, $join_behavior);
			}
		}
		$this->lastLekcjeCriteria = $criteria;

		return $this->collLekcjes;
	}

	/**
	 * Clears out the collPlanlekcjis collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPlanlekcjis()
	 */
	public function clearPlanlekcjis()
	{
		$this->collPlanlekcjis = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPlanlekcjis collection (array).
	 *
	 * By default this just sets the collPlanlekcjis collection to an empty array (like clearcollPlanlekcjis());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPlanlekcjis()
	{
		$this->collPlanlekcjis = array();
	}

	/**
	 * Gets an array of Planlekcji objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Klasy has previously been saved, it will retrieve
	 * related Planlekcjis from storage. If this Klasy is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Planlekcji[]
	 * @throws     PropelException
	 */
	public function getPlanlekcjis($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(KlasyPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPlanlekcjis === null) {
			if ($this->isNew()) {
			   $this->collPlanlekcjis = array();
			} else {

				$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

				PlanlekcjiPeer::addSelectColumns($criteria);
				$this->collPlanlekcjis = PlanlekcjiPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

				PlanlekcjiPeer::addSelectColumns($criteria);
				if (!isset($this->lastPlanlekcjiCriteria) || !$this->lastPlanlekcjiCriteria->equals($criteria)) {
					$this->collPlanlekcjis = PlanlekcjiPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPlanlekcjiCriteria = $criteria;
		return $this->collPlanlekcjis;
	}

	/**
	 * Returns the number of related Planlekcji objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Planlekcji objects.
	 * @throws     PropelException
	 */
	public function countPlanlekcjis(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(KlasyPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPlanlekcjis === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

				$count = PlanlekcjiPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

				if (!isset($this->lastPlanlekcjiCriteria) || !$this->lastPlanlekcjiCriteria->equals($criteria)) {
					$count = PlanlekcjiPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPlanlekcjis);
				}
			} else {
				$count = count($this->collPlanlekcjis);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Planlekcji object to this object
	 * through the Planlekcji foreign key attribute.
	 *
	 * @param      Planlekcji $l Planlekcji
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPlanlekcji(Planlekcji $l)
	{
		if ($this->collPlanlekcjis === null) {
			$this->initPlanlekcjis();
		}
		if (!in_array($l, $this->collPlanlekcjis, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPlanlekcjis, $l);
			$l->setKlasy($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Klasy is new, it will return
	 * an empty collection; or if this Klasy has previously
	 * been saved, it will retrieve related Planlekcjis from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Klasy.
	 */
	public function getPlanlekcjisJoinSemestr($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(KlasyPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPlanlekcjis === null) {
			if ($this->isNew()) {
				$this->collPlanlekcjis = array();
			} else {

				$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

				$this->collPlanlekcjis = PlanlekcjiPeer::doSelectJoinSemestr($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

			if (!isset($this->lastPlanlekcjiCriteria) || !$this->lastPlanlekcjiCriteria->equals($criteria)) {
				$this->collPlanlekcjis = PlanlekcjiPeer::doSelectJoinSemestr($criteria, $con, $join_behavior);
			}
		}
		$this->lastPlanlekcjiCriteria = $criteria;

		return $this->collPlanlekcjis;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Klasy is new, it will return
	 * an empty collection; or if this Klasy has previously
	 * been saved, it will retrieve related Planlekcjis from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Klasy.
	 */
	public function getPlanlekcjisJoinUzytkownik($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(KlasyPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPlanlekcjis === null) {
			if ($this->isNew()) {
				$this->collPlanlekcjis = array();
			} else {

				$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

				$this->collPlanlekcjis = PlanlekcjiPeer::doSelectJoinUzytkownik($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

			if (!isset($this->lastPlanlekcjiCriteria) || !$this->lastPlanlekcjiCriteria->equals($criteria)) {
				$this->collPlanlekcjis = PlanlekcjiPeer::doSelectJoinUzytkownik($criteria, $con, $join_behavior);
			}
		}
		$this->lastPlanlekcjiCriteria = $criteria;

		return $this->collPlanlekcjis;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Klasy is new, it will return
	 * an empty collection; or if this Klasy has previously
	 * been saved, it will retrieve related Planlekcjis from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Klasy.
	 */
	public function getPlanlekcjisJoinPrzedmiot($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(KlasyPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPlanlekcjis === null) {
			if ($this->isNew()) {
				$this->collPlanlekcjis = array();
			} else {

				$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

				$this->collPlanlekcjis = PlanlekcjiPeer::doSelectJoinPrzedmiot($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

			if (!isset($this->lastPlanlekcjiCriteria) || !$this->lastPlanlekcjiCriteria->equals($criteria)) {
				$this->collPlanlekcjis = PlanlekcjiPeer::doSelectJoinPrzedmiot($criteria, $con, $join_behavior);
			}
		}
		$this->lastPlanlekcjiCriteria = $criteria;

		return $this->collPlanlekcjis;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Klasy is new, it will return
	 * an empty collection; or if this Klasy has previously
	 * been saved, it will retrieve related Planlekcjis from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Klasy.
	 */
	public function getPlanlekcjisJoinGrupy($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(KlasyPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPlanlekcjis === null) {
			if ($this->isNew()) {
				$this->collPlanlekcjis = array();
			} else {

				$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

				$this->collPlanlekcjis = PlanlekcjiPeer::doSelectJoinGrupy($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PlanlekcjiPeer::KLASA_ID, $this->id);

			if (!isset($this->lastPlanlekcjiCriteria) || !$this->lastPlanlekcjiCriteria->equals($criteria)) {
				$this->collPlanlekcjis = PlanlekcjiPeer::doSelectJoinGrupy($criteria, $con, $join_behavior);
			}
		}
		$this->lastPlanlekcjiCriteria = $criteria;

		return $this->collPlanlekcjis;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collLekcjes) {
				foreach ((array) $this->collLekcjes as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPlanlekcjis) {
				foreach ((array) $this->collPlanlekcjis as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collLekcjes = null;
		$this->collPlanlekcjis = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseKlasy:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseKlasy::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseKlasy
