<?php

/**
 * Base class that represents a row from the 'planlekcji' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Jun 24 12:49:14 2012
 *
 * @package    lib.model.om
 */
abstract class BasePlanlekcji extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PlanlekcjiPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the semestr_id field.
	 * @var        int
	 */
	protected $semestr_id;

	/**
	 * The value for the klasa_id field.
	 * @var        int
	 */
	protected $klasa_id;

	/**
	 * The value for the nauczyciel_id field.
	 * @var        int
	 */
	protected $nauczyciel_id;

	/**
	 * The value for the przedmiot_id field.
	 * @var        int
	 */
	protected $przedmiot_id;

	/**
	 * The value for the czasstart field.
	 * @var        string
	 */
	protected $czasstart;

	/**
	 * The value for the czasstop field.
	 * @var        string
	 */
	protected $czasstop;

	/**
	 * The value for the dzientygodnia field.
	 * @var        int
	 */
	protected $dzientygodnia;

	/**
	 * The value for the godzinalekcyjna field.
	 * @var        int
	 */
	protected $godzinalekcyjna;

	/**
	 * The value for the grupa_id field.
	 * @var        int
	 */
	protected $grupa_id;

	/**
	 * The value for the obowiazkowa field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $obowiazkowa;

	/**
	 * @var        Semestr
	 */
	protected $aSemestr;

	/**
	 * @var        Klasy
	 */
	protected $aKlasy;

	/**
	 * @var        Uzytkownik
	 */
	protected $aUzytkownik;

	/**
	 * @var        Przedmiot
	 */
	protected $aPrzedmiot;

	/**
	 * @var        Grupy
	 */
	protected $aGrupy;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'PlanlekcjiPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->obowiazkowa = true;
	}

	/**
	 * Initializes internal state of BasePlanlekcji object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [semestr_id] column value.
	 * 
	 * @return     int
	 */
	public function getSemestrId()
	{
		return $this->semestr_id;
	}

	/**
	 * Get the [klasa_id] column value.
	 * 
	 * @return     int
	 */
	public function getKlasaId()
	{
		return $this->klasa_id;
	}

	/**
	 * Get the [nauczyciel_id] column value.
	 * 
	 * @return     int
	 */
	public function getNauczycielId()
	{
		return $this->nauczyciel_id;
	}

	/**
	 * Get the [przedmiot_id] column value.
	 * 
	 * @return     int
	 */
	public function getPrzedmiotId()
	{
		return $this->przedmiot_id;
	}

	/**
	 * Get the [optionally formatted] temporal [czasstart] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCzasstart($format = 'Y-m-d')
	{
		if ($this->czasstart === null) {
			return null;
		}


		if ($this->czasstart === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->czasstart);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->czasstart, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [czasstop] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCzasstop($format = 'Y-m-d')
	{
		if ($this->czasstop === null) {
			return null;
		}


		if ($this->czasstop === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->czasstop);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->czasstop, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [dzientygodnia] column value.
	 * 
	 * @return     int
	 */
	public function getDzientygodnia()
	{
		return $this->dzientygodnia;
	}

	/**
	 * Get the [godzinalekcyjna] column value.
	 * 
	 * @return     int
	 */
	public function getGodzinalekcyjna()
	{
		return $this->godzinalekcyjna;
	}

	/**
	 * Get the [grupa_id] column value.
	 * 
	 * @return     int
	 */
	public function getGrupaId()
	{
		return $this->grupa_id;
	}

	/**
	 * Get the [obowiazkowa] column value.
	 * 
	 * @return     boolean
	 */
	public function getObowiazkowa()
	{
		return $this->obowiazkowa;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Planlekcji The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PlanlekcjiPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [semestr_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Planlekcji The current object (for fluent API support)
	 */
	public function setSemestrId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->semestr_id !== $v) {
			$this->semestr_id = $v;
			$this->modifiedColumns[] = PlanlekcjiPeer::SEMESTR_ID;
		}

		if ($this->aSemestr !== null && $this->aSemestr->getId() !== $v) {
			$this->aSemestr = null;
		}

		return $this;
	} // setSemestrId()

	/**
	 * Set the value of [klasa_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Planlekcji The current object (for fluent API support)
	 */
	public function setKlasaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->klasa_id !== $v) {
			$this->klasa_id = $v;
			$this->modifiedColumns[] = PlanlekcjiPeer::KLASA_ID;
		}

		if ($this->aKlasy !== null && $this->aKlasy->getId() !== $v) {
			$this->aKlasy = null;
		}

		return $this;
	} // setKlasaId()

	/**
	 * Set the value of [nauczyciel_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Planlekcji The current object (for fluent API support)
	 */
	public function setNauczycielId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->nauczyciel_id !== $v) {
			$this->nauczyciel_id = $v;
			$this->modifiedColumns[] = PlanlekcjiPeer::NAUCZYCIEL_ID;
		}

		if ($this->aUzytkownik !== null && $this->aUzytkownik->getId() !== $v) {
			$this->aUzytkownik = null;
		}

		return $this;
	} // setNauczycielId()

	/**
	 * Set the value of [przedmiot_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Planlekcji The current object (for fluent API support)
	 */
	public function setPrzedmiotId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->przedmiot_id !== $v) {
			$this->przedmiot_id = $v;
			$this->modifiedColumns[] = PlanlekcjiPeer::PRZEDMIOT_ID;
		}

		if ($this->aPrzedmiot !== null && $this->aPrzedmiot->getId() !== $v) {
			$this->aPrzedmiot = null;
		}

		return $this;
	} // setPrzedmiotId()

	/**
	 * Sets the value of [czasstart] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Planlekcji The current object (for fluent API support)
	 */
	public function setCzasstart($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->czasstart !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->czasstart !== null && $tmpDt = new DateTime($this->czasstart)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->czasstart = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = PlanlekcjiPeer::CZASSTART;
			}
		} // if either are not null

		return $this;
	} // setCzasstart()

	/**
	 * Sets the value of [czasstop] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Planlekcji The current object (for fluent API support)
	 */
	public function setCzasstop($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->czasstop !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->czasstop !== null && $tmpDt = new DateTime($this->czasstop)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->czasstop = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = PlanlekcjiPeer::CZASSTOP;
			}
		} // if either are not null

		return $this;
	} // setCzasstop()

	/**
	 * Set the value of [dzientygodnia] column.
	 * 
	 * @param      int $v new value
	 * @return     Planlekcji The current object (for fluent API support)
	 */
	public function setDzientygodnia($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->dzientygodnia !== $v) {
			$this->dzientygodnia = $v;
			$this->modifiedColumns[] = PlanlekcjiPeer::DZIENTYGODNIA;
		}

		return $this;
	} // setDzientygodnia()

	/**
	 * Set the value of [godzinalekcyjna] column.
	 * 
	 * @param      int $v new value
	 * @return     Planlekcji The current object (for fluent API support)
	 */
	public function setGodzinalekcyjna($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->godzinalekcyjna !== $v) {
			$this->godzinalekcyjna = $v;
			$this->modifiedColumns[] = PlanlekcjiPeer::GODZINALEKCYJNA;
		}

		return $this;
	} // setGodzinalekcyjna()

	/**
	 * Set the value of [grupa_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Planlekcji The current object (for fluent API support)
	 */
	public function setGrupaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->grupa_id !== $v) {
			$this->grupa_id = $v;
			$this->modifiedColumns[] = PlanlekcjiPeer::GRUPA_ID;
		}

		if ($this->aGrupy !== null && $this->aGrupy->getId() !== $v) {
			$this->aGrupy = null;
		}

		return $this;
	} // setGrupaId()

	/**
	 * Set the value of [obowiazkowa] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Planlekcji The current object (for fluent API support)
	 */
	public function setObowiazkowa($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->obowiazkowa !== $v || $this->isNew()) {
			$this->obowiazkowa = $v;
			$this->modifiedColumns[] = PlanlekcjiPeer::OBOWIAZKOWA;
		}

		return $this;
	} // setObowiazkowa()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->obowiazkowa !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->semestr_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->klasa_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->nauczyciel_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->przedmiot_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->czasstart = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->czasstop = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->dzientygodnia = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->godzinalekcyjna = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->grupa_id = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->obowiazkowa = ($row[$startcol + 10] !== null) ? (boolean) $row[$startcol + 10] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 11; // 11 = PlanlekcjiPeer::NUM_COLUMNS - PlanlekcjiPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Planlekcji object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aSemestr !== null && $this->semestr_id !== $this->aSemestr->getId()) {
			$this->aSemestr = null;
		}
		if ($this->aKlasy !== null && $this->klasa_id !== $this->aKlasy->getId()) {
			$this->aKlasy = null;
		}
		if ($this->aUzytkownik !== null && $this->nauczyciel_id !== $this->aUzytkownik->getId()) {
			$this->aUzytkownik = null;
		}
		if ($this->aPrzedmiot !== null && $this->przedmiot_id !== $this->aPrzedmiot->getId()) {
			$this->aPrzedmiot = null;
		}
		if ($this->aGrupy !== null && $this->grupa_id !== $this->aGrupy->getId()) {
			$this->aGrupy = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PlanlekcjiPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PlanlekcjiPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aSemestr = null;
			$this->aKlasy = null;
			$this->aUzytkownik = null;
			$this->aPrzedmiot = null;
			$this->aGrupy = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PlanlekcjiPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePlanlekcji:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				PlanlekcjiPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePlanlekcji:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PlanlekcjiPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePlanlekcji:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePlanlekcji:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				PlanlekcjiPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSemestr !== null) {
				if ($this->aSemestr->isModified() || $this->aSemestr->isNew()) {
					$affectedRows += $this->aSemestr->save($con);
				}
				$this->setSemestr($this->aSemestr);
			}

			if ($this->aKlasy !== null) {
				if ($this->aKlasy->isModified() || $this->aKlasy->isNew()) {
					$affectedRows += $this->aKlasy->save($con);
				}
				$this->setKlasy($this->aKlasy);
			}

			if ($this->aUzytkownik !== null) {
				if ($this->aUzytkownik->isModified() || $this->aUzytkownik->isNew()) {
					$affectedRows += $this->aUzytkownik->save($con);
				}
				$this->setUzytkownik($this->aUzytkownik);
			}

			if ($this->aPrzedmiot !== null) {
				if ($this->aPrzedmiot->isModified() || $this->aPrzedmiot->isNew()) {
					$affectedRows += $this->aPrzedmiot->save($con);
				}
				$this->setPrzedmiot($this->aPrzedmiot);
			}

			if ($this->aGrupy !== null) {
				if ($this->aGrupy->isModified() || $this->aGrupy->isNew()) {
					$affectedRows += $this->aGrupy->save($con);
				}
				$this->setGrupy($this->aGrupy);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PlanlekcjiPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += PlanlekcjiPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSemestr !== null) {
				if (!$this->aSemestr->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSemestr->getValidationFailures());
				}
			}

			if ($this->aKlasy !== null) {
				if (!$this->aKlasy->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aKlasy->getValidationFailures());
				}
			}

			if ($this->aUzytkownik !== null) {
				if (!$this->aUzytkownik->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUzytkownik->getValidationFailures());
				}
			}

			if ($this->aPrzedmiot !== null) {
				if (!$this->aPrzedmiot->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPrzedmiot->getValidationFailures());
				}
			}

			if ($this->aGrupy !== null) {
				if (!$this->aGrupy->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aGrupy->getValidationFailures());
				}
			}


			if (($retval = PlanlekcjiPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PlanlekcjiPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getSemestrId();
				break;
			case 2:
				return $this->getKlasaId();
				break;
			case 3:
				return $this->getNauczycielId();
				break;
			case 4:
				return $this->getPrzedmiotId();
				break;
			case 5:
				return $this->getCzasstart();
				break;
			case 6:
				return $this->getCzasstop();
				break;
			case 7:
				return $this->getDzientygodnia();
				break;
			case 8:
				return $this->getGodzinalekcyjna();
				break;
			case 9:
				return $this->getGrupaId();
				break;
			case 10:
				return $this->getObowiazkowa();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PlanlekcjiPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getSemestrId(),
			$keys[2] => $this->getKlasaId(),
			$keys[3] => $this->getNauczycielId(),
			$keys[4] => $this->getPrzedmiotId(),
			$keys[5] => $this->getCzasstart(),
			$keys[6] => $this->getCzasstop(),
			$keys[7] => $this->getDzientygodnia(),
			$keys[8] => $this->getGodzinalekcyjna(),
			$keys[9] => $this->getGrupaId(),
			$keys[10] => $this->getObowiazkowa(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PlanlekcjiPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setSemestrId($value);
				break;
			case 2:
				$this->setKlasaId($value);
				break;
			case 3:
				$this->setNauczycielId($value);
				break;
			case 4:
				$this->setPrzedmiotId($value);
				break;
			case 5:
				$this->setCzasstart($value);
				break;
			case 6:
				$this->setCzasstop($value);
				break;
			case 7:
				$this->setDzientygodnia($value);
				break;
			case 8:
				$this->setGodzinalekcyjna($value);
				break;
			case 9:
				$this->setGrupaId($value);
				break;
			case 10:
				$this->setObowiazkowa($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PlanlekcjiPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setSemestrId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setKlasaId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setNauczycielId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setPrzedmiotId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCzasstart($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCzasstop($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDzientygodnia($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setGodzinalekcyjna($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setGrupaId($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setObowiazkowa($arr[$keys[10]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PlanlekcjiPeer::DATABASE_NAME);

		if ($this->isColumnModified(PlanlekcjiPeer::ID)) $criteria->add(PlanlekcjiPeer::ID, $this->id);
		if ($this->isColumnModified(PlanlekcjiPeer::SEMESTR_ID)) $criteria->add(PlanlekcjiPeer::SEMESTR_ID, $this->semestr_id);
		if ($this->isColumnModified(PlanlekcjiPeer::KLASA_ID)) $criteria->add(PlanlekcjiPeer::KLASA_ID, $this->klasa_id);
		if ($this->isColumnModified(PlanlekcjiPeer::NAUCZYCIEL_ID)) $criteria->add(PlanlekcjiPeer::NAUCZYCIEL_ID, $this->nauczyciel_id);
		if ($this->isColumnModified(PlanlekcjiPeer::PRZEDMIOT_ID)) $criteria->add(PlanlekcjiPeer::PRZEDMIOT_ID, $this->przedmiot_id);
		if ($this->isColumnModified(PlanlekcjiPeer::CZASSTART)) $criteria->add(PlanlekcjiPeer::CZASSTART, $this->czasstart);
		if ($this->isColumnModified(PlanlekcjiPeer::CZASSTOP)) $criteria->add(PlanlekcjiPeer::CZASSTOP, $this->czasstop);
		if ($this->isColumnModified(PlanlekcjiPeer::DZIENTYGODNIA)) $criteria->add(PlanlekcjiPeer::DZIENTYGODNIA, $this->dzientygodnia);
		if ($this->isColumnModified(PlanlekcjiPeer::GODZINALEKCYJNA)) $criteria->add(PlanlekcjiPeer::GODZINALEKCYJNA, $this->godzinalekcyjna);
		if ($this->isColumnModified(PlanlekcjiPeer::GRUPA_ID)) $criteria->add(PlanlekcjiPeer::GRUPA_ID, $this->grupa_id);
		if ($this->isColumnModified(PlanlekcjiPeer::OBOWIAZKOWA)) $criteria->add(PlanlekcjiPeer::OBOWIAZKOWA, $this->obowiazkowa);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PlanlekcjiPeer::DATABASE_NAME);

		$criteria->add(PlanlekcjiPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Planlekcji (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setId($this->id);

		$copyObj->setSemestrId($this->semestr_id);

		$copyObj->setKlasaId($this->klasa_id);

		$copyObj->setNauczycielId($this->nauczyciel_id);

		$copyObj->setPrzedmiotId($this->przedmiot_id);

		$copyObj->setCzasstart($this->czasstart);

		$copyObj->setCzasstop($this->czasstop);

		$copyObj->setDzientygodnia($this->dzientygodnia);

		$copyObj->setGodzinalekcyjna($this->godzinalekcyjna);

		$copyObj->setGrupaId($this->grupa_id);

		$copyObj->setObowiazkowa($this->obowiazkowa);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Planlekcji Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PlanlekcjiPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PlanlekcjiPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Semestr object.
	 *
	 * @param      Semestr $v
	 * @return     Planlekcji The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSemestr(Semestr $v = null)
	{
		if ($v === null) {
			$this->setSemestrId(NULL);
		} else {
			$this->setSemestrId($v->getId());
		}

		$this->aSemestr = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Semestr object, it will not be re-added.
		if ($v !== null) {
			$v->addPlanlekcji($this);
		}

		return $this;
	}


	/**
	 * Get the associated Semestr object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Semestr The associated Semestr object.
	 * @throws     PropelException
	 */
	public function getSemestr(PropelPDO $con = null)
	{
		if ($this->aSemestr === null && ($this->semestr_id !== null)) {
			$this->aSemestr = SemestrPeer::retrieveByPk($this->semestr_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSemestr->addPlanlekcjis($this);
			 */
		}
		return $this->aSemestr;
	}

	/**
	 * Declares an association between this object and a Klasy object.
	 *
	 * @param      Klasy $v
	 * @return     Planlekcji The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setKlasy(Klasy $v = null)
	{
		if ($v === null) {
			$this->setKlasaId(NULL);
		} else {
			$this->setKlasaId($v->getId());
		}

		$this->aKlasy = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Klasy object, it will not be re-added.
		if ($v !== null) {
			$v->addPlanlekcji($this);
		}

		return $this;
	}


	/**
	 * Get the associated Klasy object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Klasy The associated Klasy object.
	 * @throws     PropelException
	 */
	public function getKlasy(PropelPDO $con = null)
	{
		if ($this->aKlasy === null && ($this->klasa_id !== null)) {
			$this->aKlasy = KlasyPeer::retrieveByPk($this->klasa_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aKlasy->addPlanlekcjis($this);
			 */
		}
		return $this->aKlasy;
	}

	/**
	 * Declares an association between this object and a Uzytkownik object.
	 *
	 * @param      Uzytkownik $v
	 * @return     Planlekcji The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUzytkownik(Uzytkownik $v = null)
	{
		if ($v === null) {
			$this->setNauczycielId(NULL);
		} else {
			$this->setNauczycielId($v->getId());
		}

		$this->aUzytkownik = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Uzytkownik object, it will not be re-added.
		if ($v !== null) {
			$v->addPlanlekcji($this);
		}

		return $this;
	}


	/**
	 * Get the associated Uzytkownik object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Uzytkownik The associated Uzytkownik object.
	 * @throws     PropelException
	 */
	public function getUzytkownik(PropelPDO $con = null)
	{
		if ($this->aUzytkownik === null && ($this->nauczyciel_id !== null)) {
			$this->aUzytkownik = UzytkownikPeer::retrieveByPk($this->nauczyciel_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUzytkownik->addPlanlekcjis($this);
			 */
		}
		return $this->aUzytkownik;
	}

	/**
	 * Declares an association between this object and a Przedmiot object.
	 *
	 * @param      Przedmiot $v
	 * @return     Planlekcji The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPrzedmiot(Przedmiot $v = null)
	{
		if ($v === null) {
			$this->setPrzedmiotId(NULL);
		} else {
			$this->setPrzedmiotId($v->getId());
		}

		$this->aPrzedmiot = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Przedmiot object, it will not be re-added.
		if ($v !== null) {
			$v->addPlanlekcji($this);
		}

		return $this;
	}


	/**
	 * Get the associated Przedmiot object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Przedmiot The associated Przedmiot object.
	 * @throws     PropelException
	 */
	public function getPrzedmiot(PropelPDO $con = null)
	{
		if ($this->aPrzedmiot === null && ($this->przedmiot_id !== null)) {
			$this->aPrzedmiot = PrzedmiotPeer::retrieveByPk($this->przedmiot_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPrzedmiot->addPlanlekcjis($this);
			 */
		}
		return $this->aPrzedmiot;
	}

	/**
	 * Declares an association between this object and a Grupy object.
	 *
	 * @param      Grupy $v
	 * @return     Planlekcji The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setGrupy(Grupy $v = null)
	{
		if ($v === null) {
			$this->setGrupaId(NULL);
		} else {
			$this->setGrupaId($v->getId());
		}

		$this->aGrupy = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Grupy object, it will not be re-added.
		if ($v !== null) {
			$v->addPlanlekcji($this);
		}

		return $this;
	}


	/**
	 * Get the associated Grupy object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Grupy The associated Grupy object.
	 * @throws     PropelException
	 */
	public function getGrupy(PropelPDO $con = null)
	{
		if ($this->aGrupy === null && ($this->grupa_id !== null)) {
			$this->aGrupy = GrupyPeer::retrieveByPk($this->grupa_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aGrupy->addPlanlekcjis($this);
			 */
		}
		return $this->aGrupy;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aSemestr = null;
			$this->aKlasy = null;
			$this->aUzytkownik = null;
			$this->aPrzedmiot = null;
			$this->aGrupy = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePlanlekcji:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePlanlekcji::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BasePlanlekcji
