<?php

/**
 * DyplomyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DyplomyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DyplomyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dyplomy');
    }
}