<?php

/**
 * GrupyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrupyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrupyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Grupy');
    }
}