<?php

/**
 * LekcjeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LekcjeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LekcjeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lekcje');
    }
}