<?php

/**
 * ObecnosciTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObecnosciTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObecnosciTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Obecnosci');
    }
}