<?php

/**
 * OcenyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OcenyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OcenyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Oceny');
    }
}