<?php

/**
 * PlanlekcjiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanlekcjiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanlekcjiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Planlekcji');
    }
}