<?php

/**
 * PrzedmiotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrzedmiotTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrzedmiotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Przedmiot');
    }
}