<?php

/**
 * SemestrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SemestrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SemestrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Semestr');
    }
}