<?php

/**
 * TablicaocenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TablicaocenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TablicaocenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tablicaocen');
    }
}