<?php

/**
 * UsprawiedliwienieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsprawiedliwienieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsprawiedliwienieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usprawiedliwienie');
    }
}