<?php

/**
 * UwagiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UwagiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UwagiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Uwagi');
    }
}