<?php


/**
 * Skeleton subclass for representing a row from the 'tablicaocen' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * śro, 7 gru 2011, 12:49:35
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tablicaocen extends BaseTablicaocen {

} // Tablicaocen
