all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'pgsql:host=192.168.1.12;dbname=edziennik'
      username: cyryl
      password: '5015cs82cs'
      encoding: utf8
      persistent: true
      pooling: true
