all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'pgsql:host=cyryllo.no-ip.org;dbname=edziennik'
      username: cyryl
      password: 'XXXss0'
      encoding: utf8
      persistent: true
      pooling: true
