Dyplomy:
  connection: doctrine
  tableName: dyplomy
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: dyplomy_id
    pupil:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    semestr_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    przedmiot_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    ocenadyplomu:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    Przedmiot:
      local: przedmiot_id
      foreign: id
      type: one
    Uzytkownik:
      local: pupil
      foreign: id
      type: one
    Semestr:
      local: semestr_id
      foreign: id
      type: one
Grupy:
  connection: doctrine
  tableName: grupy
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: grupy_id
    pupil:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    semestr_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    grupa:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    info:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Uzytkownik:
      local: pupil
      foreign: id
      type: one
    Semestr:
      local: semestr_id
      foreign: id
      type: one
    Planlekcji:
      local: id
      foreign: grupa_id
      type: many
Klasy:
  connection: doctrine
  tableName: klasy
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: klasy_id
    poziom:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    znak:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    opis:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    wychowawca:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    startsemestr:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Uzytkownik:
      local: id
      foreign: klasa_id
      type: many
    Planlekcji:
      local: id
      foreign: klasa_id
      type: many
    Lekcje:
      local: id
      foreign: klasa_id
      type: many
Lekcje:
  connection: doctrine
  tableName: lekcje
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: lekcje_id
    przedmiot_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    klasa_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    semestr_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    temat:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    datalekcji:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    nauczyciel_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    Klasy:
      local: klasa_id
      foreign: id
      type: one
    Przedmiot:
      local: przedmiot_id
      foreign: id
      type: one
    Semestr:
      local: semestr_id
      foreign: id
      type: one
    Uzytkownik:
      local: nauczyciel_id
      foreign: id
      type: one
    Uwagi:
      local: id
      foreign: lekcja_id
      type: many
    Obecnosci:
      local: id
      foreign: lekcja_id
      type: many
Obecnosci:
  connection: doctrine
  tableName: obecnosci
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: obecnosci_id
    pupil:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    lekcja_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    rodzajobecnosci:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Lekcje:
      local: lekcja_id
      foreign: id
      type: one
    Uzytkownik:
      local: pupil
      foreign: id
      type: one
    Usprawiedliwienie:
      local: id
      foreign: obecnosci_id
      type: many
Oceny:
  connection: doctrine
  tableName: oceny
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: oceny_id
    pupil:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    ocena_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    waga:
      type: float()
      fixed: false
      unsigned: false
      notnull: true
      default: '1'
      primary: false
    nauczyciel_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    przedmiot_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    semestr_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    dataoceny:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    info:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Uzytkownik:
      local: nauczyciel_id
      foreign: id
      type: one
    Tablicaocen:
      local: ocena_id
      foreign: id
      type: one
    Przedmiot:
      local: przedmiot_id
      foreign: id
      type: one
    Uzytkownik_4:
      class: Uzytkownik
      local: pupil
      foreign: id
      type: one
    Semestr:
      local: semestr_id
      foreign: id
      type: one
Planlekcji:
  connection: doctrine
  tableName: planlekcji
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: planlekcji_id
    semestr_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    klasa_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    nauczyciel_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    przedmiot_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    czasstart:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    czasstop:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    dzientygodnia:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    godzinalekcyjna:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    grupa_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    obowiazkowa:
      type: boolean(1)
      fixed: false
      unsigned: false
      notnull: true
      default: 'true'
      primary: false
  relations:
    Grupy:
      local: grupa_id
      foreign: id
      type: one
    Klasy:
      local: klasa_id
      foreign: id
      type: one
    Uzytkownik:
      local: nauczyciel_id
      foreign: id
      type: one
    Przedmiot:
      local: przedmiot_id
      foreign: id
      type: one
    Semestr:
      local: semestr_id
      foreign: id
      type: one
Przedmiot:
  connection: doctrine
  tableName: przedmiot
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: przedmiot_id
    nazwa:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Oceny:
      local: id
      foreign: przedmiot_id
      type: many
    Dyplomy:
      local: id
      foreign: przedmiot_id
      type: many
    Planlekcji:
      local: id
      foreign: przedmiot_id
      type: many
    Lekcje:
      local: id
      foreign: przedmiot_id
      type: many
Semestr:
  connection: doctrine
  tableName: semestr
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: semestr_id
    rok:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    polowa:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Oceny:
      local: id
      foreign: semestr_id
      type: many
    Dyplomy:
      local: id
      foreign: semestr_id
      type: many
    Planlekcji:
      local: id
      foreign: semestr_id
      type: many
    Lekcje:
      local: id
      foreign: semestr_id
      type: many
    Grupy:
      local: id
      foreign: semestr_id
      type: many
Tablicaocen:
  connection: doctrine
  tableName: tablicaocen
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: tablicaocen_id
    nazwa:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    wartosc:
      type: float()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Oceny:
      local: id
      foreign: ocena_id
      type: many
Usprawiedliwienie:
  connection: doctrine
  tableName: usprawiedliwienie
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    obecnosci_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    uzytkownik_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    tresc:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Obecnosci:
      local: obecnosci_id
      foreign: id
      type: one
    Uzytkownik:
      local: uzytkownik_id
      foreign: id
      type: one
Uwagi:
  connection: doctrine
  tableName: uwagi
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: uwagi_id
    pupil:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    lekcja_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    info:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Lekcje:
      local: lekcja_id
      foreign: id
      type: one
    Uzytkownik:
      local: pupil
      foreign: id
      type: one
Uzytkownik:
  connection: doctrine
  tableName: uzytkownik
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: uzytkownik_id
    rodzaj:
      type: string(6)
      fixed: true
      unsigned: false
      notnull: false
      primary: false
    imie:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    nazwisko:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    login:
      type: string()
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    haslo:
      type: string()
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    email:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    telefon:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    klasa_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pesel:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    dataurodzin:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    miejsceurodzin:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    ojciec:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    matka:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    ulica:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    nrdomu:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    kodpocztowy:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    panstwo:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    info:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    aktywny:
      type: boolean(1)
      fixed: false
      unsigned: false
      notnull: true
      default: 'true'
      primary: false
  relations:
    Klasy:
      local: id
      foreign: wychowawca
      type: many
    Uzytkownik:
      local: id
      foreign: matka
      type: many
    Uzytkownik_3:
      class: Uzytkownik
      local: id
      foreign: ojciec
      type: many
    Oceny:
      local: id
      foreign: nauczyciel_id
      type: many
    Oceny_4:
      class: Oceny
      local: id
      foreign: pupil
      type: many
    Usprawiedliwienie:
      local: id
      foreign: uzytkownik_id
      type: many
    Dyplomy:
      local: id
      foreign: pupil
      type: many
    Planlekcji:
      local: id
      foreign: nauczyciel_id
      type: many
    Uwagi:
      local: id
      foreign: pupil
      type: many
    Lekcje:
      local: id
      foreign: nauczyciel_id
      type: many
    Grupy:
      local: id
      foreign: pupil
      type: many
    Obecnosci:
      local: id
      foreign: pupil
      type: many
